FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Build the app
RUN npm run build

# Expose the default preview port (5175)
EXPOSE 5175

# Start the server
CMD ["npm", "start"]