# 1. Builder Stage: 의존성을 설치하고 빌드하는 단계
# syntax=docker/dockerfile:1 을 맨 위에 추가하여 BuildKit 기능을 활성화합니다.
# syntax=docker/dockerfile:1
FROM python:3.11-slim as builder

WORKDIR /web

# 파이썬 환경변수 설정
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# pip 업그레이드
RUN pip install --upgrade pip

# requirements.txt를 먼저 복사하여 의존성 설치 단계를 캐시합니다.
COPY ./common/requirements.txt .
# --mount 옵션으로 pip 캐시를 마운트하고, --no-cache-dir 옵션은 제거합니다.
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY ./web/requirements.txt .
# 여기에도 동일하게 캐시 마운트를 적용합니다.
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

# 2. Final Stage: 실제 애플리케이션을 실행하는 단계
FROM python:3.11-slim

# 보안을 위해 non-root 유저 생성
RUN addgroup --system app && adduser --system --group app

WORKDIR /home/app

# Builder 스테이지에서 설치한 파이썬 패키지들을 복사합니다.
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

# 소스 코드를 복사합니다.
COPY ./web ./web
COPY ./common ./common

# 파일 소유권을 app 유저에게 부여
RUN chown -R app:app /home/app

# app 유저로 전환
USER app

# 컨테이너 실행 시 FastAPI 애플리케이션을 실행합니다.
CMD ["python","-m", "web.main"]